Testing (#37)
* appky patch

* change url for testing

* update url

* setup action

* setup actions for testing

* Testing (#28)

* appky patch

* change url for testing

* update url

* setup action

* setup actions for testing

* update action

* simulate new plugin

* Testing (#29)

* appky patch

* change url for testing

* update url

* setup action

* setup actions for testing

* simulate new plugin

* update details test

* Testing (#30)

* appky patch

* change url for testing

* update url

* setup action

* setup actions for testing

* simulate new plugin

* update details test

* add to existing package test

* Testing (#31)

* appky patch

* change url for testing

* update url

* setup action

* setup actions for testing

* simulate new plugin

* update details test

* add to existing package test

* non-config changes test

* Testing (#32)

* appky patch

* change url for testing

* update url

* setup action

* setup actions for testing

* simulate new plugin

* update details test

* add to existing package test

* non-config changes test

* fail test

* image too big

* invalid image url

* invalid appling

* add plugin without config

* add valid details

* log

* re-add details

* valid details

* Fail Testing (#33)

* appky patch

* change url for testing

* update url

* setup action

* setup actions for testing

* simulate new plugin

* update details test

* add to existing package test

* non-config changes test

* fail test

* image too big

* invalid image url

* invalid appling

* add plugin without config

* add valid details

* log

* re-add details

* valid details

* invalid to new

* last test

* fix details

* Testing (#34)

* appky patch

* change url for testing

* update url

* setup action

* setup actions for testing

* simulate new plugin

* update details test

* add to existing package test

* non-config changes test

* fail test

* image too big

* invalid image url

* invalid appling

* add plugin without config

* add valid details

* log

* re-add details

* valid details

* invalid to new

* last test

* fix details

* update icon

* Mmackz/plugin details config (#36)

* feat: add plugin details to db on pr

* refactor(builder): use required params for mint/burn

* refactor: use different logic for fetching updated config files

* refactor: change name of action

* fix: fetch origin

* docs: add comments

* feat: allow for multiple tasks

* tasks

diff --git a/.github/workflows/on-push-to-main.yml b/.github/workflows/on-push-to-main.yml
--- a/.github/workflows/on-push-to-main.yml
+++ b/.github/workflows/on-push-to-main.yml
@@ -8,70 +8,103 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  verify:
-    name: Verify
-    uses: ./.github/workflows/verify.yml
-    secrets: inherit
+  # verify:
+  #   name: Verify
+  #   uses: ./.github/workflows/verify.yml
+  #   secrets: inherit
 
-  changesets:
-    name: Changesets
+  # changesets:
+  #   name: Changesets
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 5
+
+  #   steps:
+  #     - name: Clone repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
+  #         fetch-depth: 0
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+  #         registry-url: https://registry.npmjs.org/
+  #         scope: "@rabbitholegg"
+
+  #     - name: Install dependencies
+  #       uses: ./.github/actions/install-dependencies
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  #     - name: Create Version Pull Request
+  #       uses: changesets/action@v1
+  #       with:
+  #         version: pnpm changeset:version
+  #         commit: "chore: version package"
+  #         title: "chore: version package"
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  register_new_plugins:
+    name: Register New Plugins
     runs-on: ubuntu-latest
-    timeout-minutes: 5
 
     steps:
       - name: Clone repository
         uses: actions/checkout@v4
         with:
-          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
           fetch-depth: 0
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 18
-          registry-url: https://registry.npmjs.org/
-          scope: "@rabbitholegg"
 
       - name: Install dependencies
         uses: ./.github/actions/install-dependencies
+
+      - name: Fetch target branch
+        run: git fetch origin
+
+      - name: Call API to register new plugin details without retry logic
+        run: |
+          for attempt in {1..3}; do
+            npx ts-node ./.github/scripts/registerNewPlugins.ts && break || {
+              echo "Attempt $attempt failed. Retrying in 5 seconds..."
+              sleep 5
+            }
+          done
+          if [ $attempt -eq 3 ]; then
+            echo "All attempts failed. Exiting..."
+            exit 1
+          fi
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          STAGING_API_URL: https://5efc-70-67-36-90.ngrok-free.app
+          PRODUCTION_API_URL: https://5efc-70-67-36-90.ngrok-free.app
+          BOOST_API_TOKEN: ${{ secrets.BOOST_API_TOKEN }}
 
-      - name: Create Version Pull Request
-        uses: changesets/action@v1
-        with:
-          version: pnpm changeset:version
-          commit: "chore: version package"
-          title: "chore: version package"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  # release:
+  #   name: Release
+  #   needs: verify
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 5
 
-  release:
-    name: Release
-    needs: verify
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
+  #   steps:
+  #     - name: Clone repository
+  #       uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+  #         registry-url: https://registry.npmjs.org/
+  #         scope: "@rabbitholegg"
 
-    steps:
-      - name: Clone repository
-        uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 18
-          registry-url: https://registry.npmjs.org/
-          scope: "@rabbitholegg"
+  #     - name: Install dependencies
+  #       uses: ./.github/actions/install-dependencies
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Install dependencies
-        uses: ./.github/actions/install-dependencies
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Create .npmrc
+  #       run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
 
-      - name: Create .npmrc
-        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
-
-      - name: Publish to NPM
-        uses: changesets/action@v1
-        with:
-          publish: pnpm publish-packages
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN }}
+  #     - name: Publish to NPM
+  #       uses: changesets/action@v1
+  #       with:
+  #         publish: pnpm publish-packages
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN }}
