add plugins folder for scripts

diff --git a/.github/workflows/on-push-to-main.yml b/.github/workflows/on-push-to-main.yml
--- a/.github/workflows/on-push-to-main.yml
+++ b/.github/workflows/on-push-to-main.yml
@@ -51,18 +51,27 @@ jobs:
     steps:
       - name: Clone repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Install dependencies
         uses: ./.github/actions/install-dependencies
 
-      - name: Call API to register new plugins without retry logic
-        run: npx ts-node ./.github/scripts/registerNewPlugins.ts
-        # run: |
-        #   for attempt in {1..3}; do
-        #     npx ts-node ./.github/scripts/registerNewPlugins.ts && break
-        #     echo "Attempt $attempt failed. Retrying in 5 seconds..."
-        #     sleep 5
-        #   done
+      - name: Fetch target branch
+        run: git fetch origin main:main
+
+      - name: Call API to register new plugin details without retry logic
+        run: |
+          for attempt in {1..3}; do
+            npx ts-node ./.github/scripts/plugins/registerNewPlugins.ts && break || {
+              echo "Attempt $attempt failed. Retrying in 5 seconds..."
+              sleep 5
+            }
+          done
+          if [ $attempt -eq 3 ]; then
+            echo "All attempts failed. Exiting..."
+            exit 1
+          fi
         env:
           STAGING_API_URL: https://01e0-70-67-36-90.ngrok-free.app
           PRODUCTION_API_URL: https://01e0-70-67-36-90.ngrok-free.app
