feat: setup github actions

diff --git a/.github/workflows/on-push-to-main.yml b/.github/workflows/on-push-to-main.yml
--- a/.github/workflows/on-push-to-main.yml
+++ b/.github/workflows/on-push-to-main.yml
@@ -51,23 +51,29 @@ jobs:
     steps:
       - name: Clone repository
         uses: actions/checkout@v4
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
         with:
-          node-version: 18
-          cache: 'pnpm'
+          fetch-depth: 0
 
       - name: Install dependencies
-        run: pnpm install && pnpm install node-fetch
+        uses: ./.github/actions/install-dependencies
 
-      - name: Call API to register new plugins with retry logic
+      - name: Fetch target branch
+        run: git fetch origin main:main
+
+      - name: Call API to register new plugin details without retry logic
         run: |
           for attempt in {1..3}; do
-            npx ts-node ./scripts/registerNewPlugins.ts && break
-            echo "Attempt $attempt failed. Retrying in 5 seconds..."
-            sleep 5
+            npx ts-node ./.github/scripts/registerNewPlugins.ts && break || {
+              echo "Attempt $attempt failed. Retrying in 5 seconds..."
+              sleep 5
+            }
           done
+          if [ $attempt -eq 3 ]; then
+            echo "All attempts failed. Exiting..."
+            exit 1
+          fi
+        env:
+          BOOST_API_TOKEN: ${{ secrets.BOOST_API_TOKEN }}
 
   release:
     name: Release
