Mmackz/db plugin automation (#14)
* delete test

* feat: add jojo stake plugin

* Chore: bump pnpm 8.15.3

* test

* Feat(zora): add simulateMint

* Feat(mirror): add simulateMint

* Feat(sound): add mintSimulate

* chore: format

* Chore: changeset

* Version Packages (alpha)

* add zod as a dev dependency

* add script

* add js-yaml

* update

* test

* commonjs

* things

* install types

* why not

* change

* logs

* drop catch

* set path

* add url to schema

* add test plugin

* chore: format

* update config

* add comment

* exit on error

* fill in details

* add check for new packages

* remove config

* add type notations

* branches

* target fork

* :(

* 1

* Feat(registry): add getTxSimulation to registry

* 2

* Chore: delete questk pnpm-workspace.yaml

* lfg

* types

* add details

* update message

* Fix: root tsconfig

* Fix: tweak root tsconfig

* chore: format

* Chore: changeset

* Chore: fully remove tsconfig from root

* update script

* Chore: remove per-app pnpm enforcement

* remove icon

* chore: version package (alpha)

* update

* update

* add details

* remove logs

* pass tests

* add branch

* test merge

* fix: delete TOKEN_JUSD

* Chore(utils): add sepolia to chain-ids

* Chore(types): make tokenId option for mint intent

* Fix(zora): update ABI, Save legacy mint in seperate ABI

* Feat(zora): add mint cop addresses

* Feat(utils): ADD TREASURY CONST

* Feat(zora): update intent/simulation with new contract

* Test(zora): simulation

* chore: format

* Chore: cleanup

* chore: format

* Fix: update simulation return types

* added export for tokens directory

* chore: format

* chore: format

* added changeset

* Test(zora): remove only

* Test(zora): update test data

* Chore(deps): bump codecov/codecov-action from 4.0.1 to 4.1.0

Bumps [codecov/codecov-action](https://github.com/codecov/codecov-action) from 4.0.1 to 4.1.0.
- [Release notes](https://github.com/codecov/codecov-action/releases)
- [Changelog](https://github.com/codecov/codecov-action/blob/main/CHANGELOG.md)
- [Commits](https://github.com/codecov/codecov-action/compare/v4.0.1...v4.1.0)

---
updated-dependencies:
- dependency-name: codecov/codecov-action
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Refactor(zora): use viem pad over helper

Thanks for the tip @jonathandiep

* Chore(zora): remove stray log

* Chore: changeset

* refactor(jojo): remove template comments

* refactor(jojo): convert bigint to string value

* chore: version package (alpha)

* Fix(zora): remove extra msgArgs

* chore: version package (alpha)

* validateicon

* update action

* use ngrok for testing

* Fix config file format verification script

* update iconoption

* change ngrok url

* fix logo url

* fix logo url

* verify unique urls

* add env override

* add script to register plugin details

* change install node step

* fix namespace issue

* updatefail logic

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: almo <smalljiucai@jojo.exchange>
Co-authored-by: Quazia <alf40k@gmail.com>
Co-authored-by: Quazia <Quazia@users.noreply.github.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: mmackz <mmackz@users.noreply.github.com>
Co-authored-by: veganbeef <veganbeef@protonmail.com>
Co-authored-by: veganbeef <veganbeef@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/on-push-to-main.yml b/.github/workflows/on-push-to-main.yml
--- a/.github/workflows/on-push-to-main.yml
+++ b/.github/workflows/on-push-to-main.yml
@@ -58,10 +58,14 @@ jobs:
       - name: Call API to register new plugins with retry logic
         run: |
           for attempt in {1..3}; do
-            npx ts-node ./.github/scripts/registerNewPlugins.ts && break
-            echo "Attempt $attempt failed. Retrying in 5 seconds..."
+            npx ts-node ./.github/scripts/registerNewPlugins.ts && break 
+            || echo "Attempt $attempt failed. Retrying in 5 seconds..."
             sleep 5
           done
+          if [ $attempt -eq 3 ]; then
+            echo "All attempts failed. Exiting..."
+            exit 1
+          fi
         env:
           STAGING_API_URL: https://01e0-70-67-36-90.ngrok-free.app
           PRODUCTION_API_URL: https://01e0-70-67-36-90.ngrok-free.app
