appky patch

diff --git a/.github/workflows/on-push-to-main.yml b/.github/workflows/on-push-to-main.yml
--- a/.github/workflows/on-push-to-main.yml
+++ b/.github/workflows/on-push-to-main.yml
@@ -44,6 +44,37 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+  register_new_plugins:
+    name: Register New Plugins
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Clone repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Install dependencies
+        uses: ./.github/actions/install-dependencies
+
+      - name: Fetch target branch
+        run: git fetch origin main:main
+
+      - name: Call API to register new plugin details without retry logic
+        run: |
+          for attempt in {1..3}; do
+            npx ts-node ./.github/scripts/registerNewPlugins.ts && break || {
+              echo "Attempt $attempt failed. Retrying in 5 seconds..."
+              sleep 5
+            }
+          done
+          if [ $attempt -eq 3 ]; then
+            echo "All attempts failed. Exiting..."
+            exit 1
+          fi
+        env:
+          BOOST_API_TOKEN: ${{ secrets.BOOST_API_TOKEN }}
+
   release:
     name: Release
     needs: verify
